# Generated by Django 4.2.7 on 2025-10-29 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mariadb_backend.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_vector",
                    mariadb_backend.fields.VectorField(
                        blank=True,
                        help_text="User interest vector for recommendations",
                        max_length=8192,
                        null=True,
                    ),
                ),
                (
                    "preferences",
                    mariadb_backend.fields.EnhancedJSONField(
                        default=dict,
                        help_text="User preferences: theme, notifications, etc.",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                (
                    "content_vector",
                    mariadb_backend.fields.VectorField(
                        blank=True,
                        help_text="Embedding vector for semantic search",
                        max_length=8192,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    mariadb_backend.fields.EnhancedJSONField(
                        default=dict,
                        help_text="Post metadata: tags, categories, SEO, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                mariadb_backend.fields.VectorQueryMixin,
                mariadb_backend.fields.JSONQueryMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "metadata",
                    mariadb_backend.fields.EnhancedJSONField(
                        default=dict,
                        help_text="Comment metadata: sentiment, flagged, edited, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog_demo.post",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "metrics",
                    mariadb_backend.fields.EnhancedJSONField(
                        default=dict,
                        help_text="Daily metrics: views, clicks, time_on_page, etc.",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="blog_demo.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="blog_demo_p_created_9e0b9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="blog_demo_p_slug_96fda8_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["published", "-created_at"],
                name="blog_demo_p_publish_3d759d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analytics",
            unique_together={("post", "date")},
        ),
    ]
