# Generated by Django 4.2.7 on 2025-10-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analytics",
            name="metrics",
            field=models.JSONField(
                default=dict,
                help_text="Daily metrics: views, clicks, time_on_page, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="metadata",
            field=models.JSONField(
                default=dict,
                help_text="Comment metadata: sentiment, flagged, edited, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="metadata",
            field=models.JSONField(
                default=dict, help_text="Post metadata: tags, categories, SEO, etc."
            ),
        ),
    ]
